'use server'

import { stream } from '@chatbotkit/react/utils/stream'

/**
 * We use this function to add a delay between each yielded object.
 *
 * @param {number} ms
 * @returns {Promise<void>}
 */
async function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

/**
 * This is the main server-side function that generates objects. This is a
 * simple example that generates an object with a random number every second.
 *
 * @returns {AsyncGenerator<{ random: number }>}
 */
export async function* generateObjects() {
  while (true) {
    yield { random: Math.random() }

    await sleep(1000)
  }
}

/**
 * This function facilitates streaming the objects generated by wrapping each
 * result in a consumable stream.
 */
export async function streamObjects() {
  return stream(generateObjects())
}
