packages:
  - 'packages/*'
  - 'tools/*'
  - 'examples/sdk'
  - 'examples/agent'
  - 'examples/nextjs/pages/*'
  - 'examples/nextjs/app/*'
  - 'examples/nextjs/hybrid/*'
  - 'examples/cloudflare/*'
  - 'examples/vite/react/*'
