packages:
  - 'packages/fetch'
  - 'packages/sdk'
  - 'packages/cli'
  - 'packages/react'
  - 'packages/next'
  - 'packages/nextauth'
  - 'examples/sdk/*'
  - 'examples/nextjs/pages/*'
  - 'examples/nextjs/app/*'
  - 'examples/cloudflare/*'
