export class ChatBotKit extends ChatBotKitClient {
    platform: PlatformClient;
    blueprint: BlueprintClient;
    bot: BotClient;
    file: FileClient;
    magic: MagicClient;
    partner: PartnerClient;
    dataset: DatasetClient;
    skillset: SkillsetClient;
    integration: IntegrationClient;
    conversation: ConversationClient;
    contact: ContactClient;
    task: TaskClient;
    usage: UsageClient;
    secrets: SecretClient;
    graphql: GraphqlClient;
}
export default ChatBotKit;
import { BotClient } from './bot/index.js';
import { FileClient } from './file/index.js';
import { MagicClient } from './magic/index.js';
import { PartnerClient } from './partner/index.js';
import { DatasetClient } from './dataset/index.js';
import { SkillsetClient } from './skillset/index.js';
import { IntegrationClient } from './integration/index.js';
import { ConversationClient } from './conversation/index.js';
import { ContactClient } from './contact/index.js';
import { SecretClient } from './secret/index.js';
import { BlueprintClient } from './blueprint/index.js';
import { GraphqlClient } from './graphql/index.js';
import { UsageClient } from './usage/index.js';
import { ChatBotKitClient } from './client.js';
import { PlatformClient } from './platform/index.js';
import { TaskClient } from './task/index.js';
export { BotClient, FileClient, MagicClient, PartnerClient, DatasetClient, SkillsetClient, IntegrationClient, ConversationClient, ContactClient, SecretClient, BlueprintClient, GraphqlClient, UsageClient };
