export class ChatBotKit extends ChatBotKitClient {
    platform: PlatformClient;
    blueprint: BlueprintClient;
    bot: BotClient;
    channel: ChannelClient;
    file: FileClient;
    secret: SecretClient;
    magic: MagicClient;
    partner: PartnerClient;
    dataset: DatasetClient;
    skillset: SkillsetClient;
    integration: IntegrationClient;
    team: TeamClient;
    contact: ContactClient;
    space: SpaceClient;
    task: TaskClient;
    conversation: ConversationClient;
    memory: MemoryClient;
    policy: PolicyClient;
    portal: PortalClient;
    report: ReportClient;
    usage: UsageClient;
    graphql: GraphqlClient;
}
export default ChatBotKit;
import { BlueprintClient } from './blueprint/index.js';
import { BotClient } from './bot/index.js';
import { ChannelClient } from './channel/index.js';
import { FileClient } from './file/index.js';
import { MagicClient } from './magic/index.js';
import { PartnerClient } from './partner/index.js';
import { DatasetClient } from './dataset/index.js';
import { SkillsetClient } from './skillset/index.js';
import { IntegrationClient } from './integration/index.js';
import { ConversationClient } from './conversation/index.js';
import { ContactClient } from './contact/index.js';
import { SecretClient } from './secret/index.js';
import { TeamClient } from './team/index.js';
import { MemoryClient } from './memory/index.js';
import { PolicyClient } from './policy/index.js';
import { PortalClient } from './portal/index.js';
import { ReportClient } from './report/index.js';
import { GraphqlClient } from './graphql/index.js';
import { SpaceClient } from './space/index.js';
import { UsageClient } from './usage/index.js';
import { ChatBotKitClient } from './client.js';
import { PlatformClient } from './platform/index.js';
import { TaskClient } from './task/index.js';
export { BlueprintClient, BotClient, ChannelClient, FileClient, MagicClient, PartnerClient, DatasetClient, SkillsetClient, IntegrationClient, ConversationClient, ContactClient, SecretClient, TeamClient, MemoryClient, PolicyClient, PortalClient, ReportClient, GraphqlClient, SpaceClient, UsageClient };
